version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npx nodemon src/index.js
    volumes:
      - ./src:/app/src
    environment:
      NODE_ENV: development
